# CLEANING DATASET

In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/matches.csv")
print(df.head())

   id  season       city      date                        team1  \
0   1    2017  Hyderabad  5/4/2017          Sunrisers Hyderabad
1   2    2017       Pune  6/4/2017               Mumbai Indians
2   3    2017     Rajkot  7/4/2017                Gujarat Lions
3   4    2017     Indore  8/4/2017       Rising Pune Supergiant
4   5    2017  Bangalore  8/4/2017  Royal Challengers Bangalore

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field
1       Rising Pune Supergiant       Rising Pune Supergiant         field
2        Kolkata Knight Riders        Kolkata Knight Riders         field
3              Kings XI Punjab              Kings XI Punjab         field
4             Delhi Daredevils  Royal Challengers Bangalore           bat

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35
1  normal           0       Rising Pune Supergiant            0
2  normal           0        Kolkata Knight Riders            0
3  normal           0              Kings XI Punjab            0
4  normal           0  Royal Challengers Bangalore           15

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal
1               7       SPD Smith    Maharashtra Cricket Association Stadium
2              10         CA Lynn     Saurashtra Cricket Association Stadium
3               6      GJ Maxwell                     Holkar Cricket Stadium
4               0       KM Jadhav                      M Chinnaswamy Stadium

          umpire1        umpire2  umpire3
0     AY Dandekar       NJ Llong      NaN
1  A Nand Kishore         S Ravi      NaN
2     Nitin Menon      CK Nandan      NaN
3    AK Chaudhary  C Shamshuddin      NaN
4             NaN            NaN      NaN

In [8]:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

In [9]:
df[df.isnull().any(axis=1)]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,22/05/16,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,24/05/16,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,25/05/16,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,27/05/16,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,29/05/16,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [11]:
df.drop('umpire3', axis=1, inplace=True)

In [12]:
df = df.dropna()

In [13]:
df.isnull().sum()

id                 0
season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             0
win_by_runs        0
win_by_wickets     0
player_of_match    0
venue              0
umpire1            0
umpire2            0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [16]:
df.to_csv("Cleaned_matches.csv",index=False)

# ANALYZING DATA

In [30]:
#TOP RUNNER SCORER
runs=df.groupby('winner')['win_by_runs'].sum()
top_teams=runs.sort_values(ascending=False)
print("******************TOP RUNNER SCORER*********************")
print(top_teams)
print("********************************************************")

******************TOP RUNNER SCORER*********************
winner
Chennai Super Kings            1587
Mumbai Indians                 1532
Royal Challengers Bangalore    1196
Kolkata Knight Riders           897
Kings XI Punjab                 862
Rajasthan Royals                821
Delhi Daredevils                571
Sunrisers Hyderabad             476
Deccan Chargers                 421
Pune Warriors                   139
Rising Pune Supergiant          123
Rising Pune Supergiants          53
Kochi Tuskers Kerala             23
Gujarat Lions                     1
No Result                         0
Name: win_by_runs, dtype: int64
********************************************************

In [31]:
#TEAMS WITH MOST WICKETS
wickets=df.groupby('winner')['win_by_wickets'].sum()
top_teams=wickets.sort_values(ascending=False)
print("****************TEAMS HAVING MOST WICKETS*****************")
print(top_teams)
print("**********************************************************")

****************TEAMS HAVING MOST WICKETS*****************
winner
Kolkata Knight Riders          291
Royal Challengers Bangalore    277
Mumbai Indians                 270
Delhi Daredevils               268
Rajasthan Royals               233
Kings XI Punjab                227
Chennai Super Kings            208
Sunrisers Hyderabad            117
Deccan Chargers                 72
Gujarat Lions                   65
Pune Warriors                   36
Rising Pune Supergiant          31
Kochi Tuskers Kerala            30
Rising Pune Supergiants         20
No Result                        0
Name: win_by_wickets, dtype: int64
**********************************************************

In [36]:
#WINNING PERCENTAGE
t1=df['team1'].value_counts()
t2=df['team2'].value_counts()
total=t1.add(t2, fill_value=0)
wins=df['winner'].value_counts()
winning_percentage=(wins/total)*100
data= winning_percentage.sort_values(ascending=False)
print("******************** TEAM WINNING PERCENTAGE ********************")
print(data)
print("*****************************************************************")

******************** TEAM WINNING PERCENTAGE ********************
Rising Pune Supergiant         62.500000
Chennai Super Kings            60.305344
Mumbai Indians                 58.598726
Sunrisers Hyderabad            55.263158
Rajasthan Royals               53.389831
Kolkata Knight Riders          52.027027
Royal Challengers Bangalore    48.026316
Kings XI Punjab                47.297297
Gujarat Lions                  43.333333
Kochi Tuskers Kerala           42.857143
Delhi Daredevils               42.176871
Deccan Chargers                38.666667
Rising Pune Supergiants        35.714286
Pune Warriors                  26.086957
No Result                            NaN
Name: count, dtype: float64
*****************************************************************

In [49]:
#TOSS IMPACT ANALYSIS
total=len(df)
toss_wins=(df['toss_winner']==df['winner']).sum()
print("*****************TOSS IMPACT ANALYSIS*************************")
print(f"Total Matches:{total}")
print(f"Matches Won:{toss_wins}")
result=(toss_wins/total)*100
print(f"Toss Impact Percentage:{result:.2f}%")
print("**************************************************************")

*****************TOSS IMPACT ANALYSIS*************************
Total Matches:636
Matches Won:325
Toss Impact Percentage:51.10%
**************************************************************